const PROPERTY_LIST_REQUEST = "PROPERTY_LIST_REQUEST";
const PROPERTY_LIST_SUCCESS = "PROPERTY_LIST_SUCCESS";
const PROPERTY_LIST_FAIL = "PROPERTY_LIST_FAIL";

export { PROPERTY_LIST_FAIL, PROPERTY_LIST_REQUEST, PROPERTY_LIST_SUCCESS };
