const PROPERTY_LIST_REQUEST = "PROPERTY_LIST_REQUEST";
const PROPERTY_LIST_SUCCESS = "PROPERTY_LIST_SUCCESS";
const PROPERTY_LIST_FAIL = "PROPERTY_LIST_FAIL";
const PROPERTY_ADD_REQUEST = "PROPERTY_ADD_REQUEST";
const PROPERTY_ADD_SUCCESS = "PROPERTY_ADD_SUCCESS";
const PROPERTY_ADD_FAIL = "PROPERTY_ADD_FAIL";

export {
  PROPERTY_LIST_FAIL,
  PROPERTY_LIST_REQUEST,
  PROPERTY_LIST_SUCCESS,
  PROPERTY_ADD_FAIL,
  PROPERTY_ADD_REQUEST,
  PROPERTY_ADD_SUCCESS,
};
